language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=4.x-dev

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL
    - php: 7.2
      env: DB=MYSQL
    - php: 7.3
      env: DB=MYSQL

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit
